import type { Client } from './types'

export const clients: Client[] = [
  {
    id: 'suzanne',
    name: 'Suzanne',
    programName: '10-Week Golf Strength + Hip Mobility Program',
    currentWeek: 1,
    totalWeeks: 10,
    workoutsCompleted: 2,
    totalWorkouts: 30,
    assessment: {
      goal: 'Improve golf strength, hip mobility, and confidence during movement.',
      movementNotes: 'Limited hip rotation on loading side. Needs controlled mobility work.',
      strengthNotes: 'Lower-body strength needs improvement, especially hip stability.',
      cardioNotes: 'Can tolerate moderate walking but needs gradual endurance progression.',
      trainerFocus:
        'Mobility, balance, core stability, lower-body strength, and rotational control.',
    },
    workouts: [
      {
        id: 'w1-a',
        title: 'Workout A — Golf Strength Foundation',
        week: 1,
        day: 'Day 1',
        focus: 'Lower-body strength, hip mobility, and core control',
        status: 'today',
        exercises: [
          {
            id: 'ex1',
            name: 'Bike Warm-Up',
            category: 'Warm-Up',
            sets: '1',
            reps: '6 minutes',
            rest: 'None',
            notes: 'Easy pace. Focus on smooth breathing.',
          },
          {
            id: 'ex2',
            name: 'Hip Mobility Flow',
            category: 'Mobility',
            sets: '2',
            reps: '30 seconds each side',
            rest: '30 sec',
            notes: 'Move slowly and stay within a comfortable range.',
          },
          {
            id: 'ex3',
            name: 'Dead Bug',
            category: 'Core Activation',
            sets: '2',
            reps: '8 each side',
            rest: '45 sec',
            notes: 'Keep low back controlled. Do not rush.',
          },
          {
            id: 'ex4',
            name: 'Goblet Box Squat',
            category: 'Resistance Training',
            sets: '3',
            reps: '10',
            rest: '60 sec',
            notes: 'Sit back to the box. Keep chest tall and knees stable.',
          },
          {
            id: 'ex5',
            name: 'Seated Row',
            category: 'Resistance Training',
            sets: '3',
            reps: '10–12',
            rest: '60 sec',
            notes: 'Pull elbows back. Keep shoulders relaxed.',
          },
        ],
      },
      {
        id: 'w1-b',
        title: 'Workout B — Mobility + Core Stability',
        week: 1,
        day: 'Day 2',
        focus: 'Hip control, balance, and core endurance',
        status: 'upcoming',
        exercises: [
          {
            id: 'ex6',
            name: 'Treadmill Walk',
            category: 'Warm-Up',
            sets: '1',
            reps: '8 minutes',
            rest: 'None',
            notes: 'Comfortable walking pace.',
          },
          {
            id: 'ex7',
            name: 'Pallof Press',
            category: 'Core Activation',
            sets: '2',
            reps: '10 each side',
            rest: '45 sec',
            notes: 'Resist rotation. Keep ribs down.',
          },
          {
            id: 'ex8',
            name: 'Step-Ups',
            category: 'Resistance Training',
            sets: '2',
            reps: '8 each side',
            rest: '60 sec',
            notes: 'Use support if needed. Control the lowering.',
          },
        ],
      },
    ],
  },
  {
    id: 'robert',
    name: 'Robert',
    programName: '10-Week Seated Strength + Stability Program',
    currentWeek: 1,
    totalWeeks: 10,
    workoutsCompleted: 1,
    totalWorkouts: 20,
    assessment: {
      goal: 'Maintain strength safely while respecting hernia limitations.',
      movementNotes: 'Needs mostly seated exercises and careful intensity control.',
      strengthNotes: 'Good effort but needs low-strain progressions.',
      cardioNotes: 'Short low-intensity bike work is preferred.',
      trainerFocus:
        'Seated strength, posture, breathing control, and avoiding aggravating movements.',
    },
    workouts: [
      {
        id: 'r1-a',
        title: 'Workout A — Seated Strength',
        week: 1,
        day: 'Day 1',
        focus: 'Safe seated resistance training',
        status: 'today',
        exercises: [
          {
            id: 'rex1',
            name: 'Recumbent Bike',
            category: 'Warm-Up',
            sets: '1',
            reps: '6 minutes',
            rest: 'None',
            notes: 'Low intensity. Stop if discomfort appears.',
          },
          {
            id: 'rex2',
            name: 'Seated Leg Curl',
            category: 'Resistance Training',
            sets: '2',
            reps: '12',
            rest: '60 sec',
            notes: 'Smooth reps. Avoid breath holding.',
          },
          {
            id: 'rex3',
            name: 'Seated Chest Press',
            category: 'Resistance Training',
            sets: '2',
            reps: '10',
            rest: '60 sec',
            notes: 'Light to moderate only. Exhale during effort.',
          },
        ],
      },
    ],
  },
]